### ISSUE TITLE
AxiosResponse.request 始终为 null

### ISSUE THREAD

**Issue by Rhilip** [Trim21/axios-userscript-adapter#13]
在写请求时，发现 axios 返回的response中request始终为null。
![image](https://user-images.githubusercontent.com/13842140/92340380-aafee100-f0ec-11ea-8f92-54abbf0eac0b.png)

这样就有一些操作，比如xhr的finalUrl等信息无法进行获取判断。

查阅源码，发现在请求返回中request直接置为 null 值，请问这一块是无法转化实现吗？

https://github.com/Trim21/axios-userscript-adapter/blob/39b6946d734f2b17fcb3321c658ef83ee84c4e4a/src/index.js#L74

但是另一位相关作者的方法中， request应该是能够获取到的。还请解答。
https://github.com/damoclark/axios-gmxhr-adapter/blob/master/lib/adapters/gm.js#L75

**Comment by Trim21** [comment]
这个作者是把GM_xmlhttpRequest给包装成了一个request对象，实际是拿不到的。

**Comment by Trim21** [comment]
我想想finalUrl的问题怎么解决，GM_xmlhttpRequest是可以拿到的

**Comment by Trim21** [comment]
```js
        request: {
          // can't got real XMLHttpRequest object, only some property is available
          responseURL: resp.finalUrl,
          status: resp.status,
          statusText: resp.statusText,
          responseXML: null,
        }
```

看了一下文档大概能转换的属性只有这些，还有一些方法之类实现起来就没有意义了。

**Comment by Trim21** [comment]
升级到0.0.7即可
