### ISSUE TITLE
没有遵守 `baseURL` 配置项

### ISSUE THREAD

**Issue by Rhilip** [Trim21/axios-userscript-adapter#25]
# Description

目前用的 v0.7.0 版本（因为未使用 `GM.*` 方法，故未升级），

测试中使用 以下代码：

```javascript
axios.request({
   baseURL: 'https://xxxx.xxx.xxx',
   url: '/xxx'
})
```
进行页面请求，会发现请求出错，插件背景页显示的请求地址仍为 脚本运行页面，而不是设定的 baseURL 地址。

对比 v0.7.0 版本 和目前版本，其请求链接生成方式相同，应该同样存在相同问题。

~~应该在 `buildURL` 外再套一层 `buildFullPath` 。~~

按照 axios的写法，应该写成 

```javascript
url: buildURL(buildFullPath(config.baseURL, config.url), config.params, config.paramsSerializer),
```

## How to reproduce

见上

## Environment

- language version:
- app/lib/repo version:

**Comment by Trim21** [comment]
好像没有0.7.0版本啊（

**Comment by Trim21** [comment]
我就不backport回0.0.7了 = = 原谅我的懒惰

**Comment by Rhilip** [comment]
> 好像没有0.7.0版本啊（

是我写错了2333

> 我就不backport回0.0.7了 = = 原谅我的懒惰

问题不大，就一个ts文件，我自己copy下就行，就不用npm库了。。
