### ISSUE TITLE
GM_xmlhttprequest

### ISSUE THREAD

**Issue by magicdawn** [Trim21/axios-userscript-adapter#54]
TamperMonkey / ViolentMonkey only provide `GM_xmlhttprequest`
can U add an option to config this? or just detect at runtime

current I'm using webpack provide to do the rename stuff

```ts
// webpack.config.js
new ProvidePlugin({   
   GM: __dirname + '/src/GM.ts',
 })

// src/GM.ts
export const xmlHttpRequest = GM_xmlhttpRequest
```

**Comment by Trim21** [comment]
I'm pretty sure TamperMonkey provide `GM` object and it's http request API.

**Comment by Trim21** [comment]
And violent monkey also provide this API https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest

**Comment by Trim21** [comment]
you need to grant the permission of `GM.xmlHttprequest` instead of `GM_xmlhttprequest`

**Comment by magicdawn** [comment]
Thanks.  I missed that part of violentmonkey doc.
